steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/gcpdevops-ocean-434308-j4/runimage', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/gcpdevops-ocean-434308-j4/runimage']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'runwithcicd', '--image', 'us.gcr.io/gcpdevops-ocean-434308-j4/runimage', '--region', 'us-central1', '--allow-unauthenticated']
images:
- us.gcr.io/gcpdevops-ocean-434308-j4/runimage
options:
  logging : CLOUD_LOGGING_ONLY 
